# Generated by Django 4.2.16 on 2025-05-14 05:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('is_at_client', models.BooleanField(default=False, verbose_name='У клиента')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Тара',
                'verbose_name_plural': 'Тара',
            },
        ),
    ]
