# Generated by Django 4.2.16 on 2025-05-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='region',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
