# Generated by Django 4.2.16 on 2025-05-21 03:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_route_routeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('min_monthly_volume', models.PositiveIntegerField(help_text='Минимальный объем в литрах для категории')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_per_liter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points_to_money_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_points_to_redeem', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='routeorder',
            options={'ordering': ['order_number'], 'verbose_name': 'Заказ в маршруте', 'verbose_name_plural': 'Заказы в маршруте'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='region',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.RemoveField(
            model_name='routeorder',
            name='order_index',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('business', 'Юридическое лицо')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_volume_purchased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='call_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_confirmations/'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('points', 'Баллы'), ('mixed', 'Смешанная')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='points_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='points_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routeorder',
            name='order_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('planned', 'Запланирован'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменён')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order'),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.route'),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('earned', 'Начислено'), ('redeemed', 'Списано'), ('expired', 'Сгорело')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.order')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.clientcategory'),
        ),
    ]
