# Generated by Django 4.2.16 on 2025-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
